### PR TITLE
fix for issue 6

### PR DESCRIPTION
**Pull request by nemgrea**

### CODE REVIEW

**Comment by Roycinger** [comment]
I just compared the new latch shuttle to the new one. 
To me, they look exactly the same without any change.
image
(new on the left, old on the right)
Can you please elaborate how this fixes issue 6?

**Comment by nemgrea** [comment]
They are the same, the name was changed to include [a]

**Comment by nemgrea** [comment]
Thus is the switchwire repo issue #6

**Comment by Roycinger** [comment]
Gotcha. I thought it was misleadingly related to AB's Issue 6.

**Pull request merged**
